# -*- coding: utf-8 -*-
"""real_time_fraud_transactions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ydkRGUE8ivoz7izOhsqqNF6-vtolGxsE
"""

import datetime
import uuid
import random
import pandas as pd
from datetime import datetime, timedelta

# Generate a fresh synthetic transaction dataset for real-time fraud detection
# Define parameters
num_records = 10000  # Number of transactions
start_date = datetime(2024, 1, 1)
end_date = datetime(2024, 12, 31)

# List of merchant categories
merchant_categories = [
    "Electronics", "Groceries", "Clothing", "Gas Station", "Online Purchase",
    "Subscription Service", "Luxury Goods", "Fast Food", "Travel", "Entertainment"
]

# Generate transaction data
data = []
for _ in range(num_records):
    transaction_id = str(uuid.uuid4())
    user_id = random.randint(1000, 9999)  # Simulating unique users
    timestamp = start_date + timedelta(seconds=random.randint(0, int((end_date - start_date).total_seconds())))
    amount = round(random.uniform(1, 5000), 2)  # Transaction amount between $1 and $5000
    merchant = random.choice(merchant_categories)
    location = random.choice(["New York", "Los Angeles", "Chicago", "Houston", "San Francisco", "Miami", "Seattle"])
    payment_method = random.choice(["Credit Card", "Debit Card", "PayPal", "Bitcoin"])
    is_fraud = random.choices([0, 1], weights=[0.98, 0.02], k=1)[0]  # 2% fraud rate

    data.append([transaction_id, user_id, timestamp, amount, merchant, location, payment_method, is_fraud])

# Create DataFrame
df = pd.DataFrame(data, columns=[
    "transaction_id", "user_id", "timestamp", "amount", "merchant_category",
    "location", "payment_method", "is_fraud"
])

import datetime
import uuid
import random
import pandas as pd
from datetime import datetime, timedelta

# ... (rest of your code to generate the dataframe df remains unchanged)

# Mount Google Drive **before** saving the file.
from google.colab import drive
drive.mount('/content/drive')

# Save dataset as CSV
# Changed the file path by removing the leading single quote, which was causing issues.
dataset_path = "/content/drive/MyDrive/real_time_fraud_transactions.csv"
df.to_csv(dataset_path, index=False)

# Provide dataset for download
print(f"Dataset saved as {dataset_path}")

from google.colab import drive
drive.mount('/content/drive')